"""create missing tables

Revision ID: 374b92a5dd96
Revises: be56a167097f
Create Date: 2026-02-21 22:53:30.744677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374b92a5dd96'
down_revision: Union[str, Sequence[str], None] = 'be56a167097f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('mon', sa.Boolean(), nullable=True),
    sa.Column('tue', sa.Boolean(), nullable=True),
    sa.Column('wed', sa.Boolean(), nullable=True),
    sa.Column('thu', sa.Boolean(), nullable=True),
    sa.Column('fri', sa.Boolean(), nullable=True),
    sa.Column('sat', sa.Boolean(), nullable=True),
    sa.Column('sun', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_settings_id'), 'clinic_settings', ['id'], unique=False)
    op.create_table('appointment_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_blocks_id'), 'appointment_blocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_blocks_id'), table_name='appointment_blocks')
    op.drop_table('appointment_blocks')
    op.drop_index(op.f('ix_clinic_settings_id'), table_name='clinic_settings')
    op.drop_table('clinic_settings')
    # ### end Alembic commands ###
